sudo: required
language: cpp
branches:
  except:
  - /^\d\d\d\d\d\d\d\d\d\d\d\d\d\d-[\da-f]+$/

services:
- docker

env:
  global:
  - secure: FlsmywHiGR6VKejCGcEd59rhvk5YI1f+FUAWfBLVxzqG4haLGT0MQwyxDr2EPS3Iu+v16nsMxHT2dwMCotC8zTPSmHUr6evE4jpNcqs+vIOAz7VLjdqwD0jweeguOR4JxL1XcgFZMAPTnoQFBFZlEOFu8OxaDjOoG7Oj0iGH+Fo=
  - DISTRIB=travis-ubuntu16.04
  - DISTRIB=debian9.4

script: docker build --tag $DISTRIB --build-arg JOB_NUMBER=$TRAVIS_JOB_NUMBER
  -f ./Dockerfile-$DISTRIB .

after_success:
- docker run -t -d lima-ubuntu16
- docker cp $(docker ps -n 1 -q):/usr/share/apps/lima/packages $HOME
- docker stop lima-ubuntu16
- docker run -t -d lima-debian9
- docker cp $(docker ps -n 1 -q):/usr/share/apps/lima/packages/ $HOME

before_deploy:
- git config --local user.name "Gael de Chalendar"
- git config --local user.email "kleag@free.fr"
- git tag "$(git log --date=iso  -1 | grep Date | sed -e 's/Date:\ *//' -e 's/\+.*//' -e 's/[- :]//g')-$(git log --format=%h --abbrev=8 -1)" || true

deploy:
  provider: releases
  api_key:
    secure: u0jcRYK9fsJ9ymnpU8ET5dd/DZ/rwah2WhOrfQGUkBM+VB2ASol1KCz8EMMwNQM44echMHz6LwxWM9np9vBUZZCgt/riU/vEVW7Dkmjyiwbscov7qbDmsLDdQy7LxFpEh+dA8m6U9thyWxBdtoDzDX8+3G0Oxfjf4cIa3eyAFv0=
  file_glob: true
  file: $HOME/packages/*.deb
  skip_cleanup: true
  on:
    repo: aymara/lima
    tags: false
    branches:
      except:
      - /^\d\d\d\d\d\d\d\d\d\d\d\d\d\d-[\da-f]+$/
