#init:
 #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  LIMA_DIST: c:\d
  LIMA_CONF: 'c:\d\share\config\lima'
  LIMA_RESOURCES: 'c:\d\share\apps\lima\resources'
  QTDIR: 'C:\Qt\5.8\msvc2015_64'
  BOOST_ROOT: 'C:\Libraries\boost_1_63_0'
  BOOST_LIBRARYDIR: 'C:\Libraries\boost_1_63_0\lib64-msvc-14.0'
  PATH: '%QTDIR%\bin;c:\d\bin;c:\d\share\apps\lima\scripts;%BOOST_LIBRARYDIR%;c:\msys64\usr\bin;%PATH%'
  LIMA_DISABLE_FSW_TESTING: true
  NLTK_PTB_DP_DIR: 'c:\dependency_treebank'
  NLTK_PTB_DP_FILE: 'c:\dependency_treebank\nltk-ptb.dp'
  GITHUB_OAUTH_TOKEN:
    secure: 01sh5OxKgkUJbTt/ldX/duLQk6iP28Iwet3reW8FK8f7Z3xiM2RLHQUwOzZye4qs

  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

configuration: Release

os: Visual Studio 2015
#os: Visual Studio 2013

install:
  # Prepend chosen Python to the PATH of this build
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  ############################################################################
  # All external dependencies are installed in C:\externals
  ############################################################################
  - mkdir C:\externals
  - cd C:\externals

  ############################################################################
  # Install Ninja
  ############################################################################
  - appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip -FileName ninja.zip
  - 7z x ninja.zip -oC:\externals\ninja > nul
  - set PATH=C:\externals\ninja;%PATH%
  - ninja --version

  - ps: (new-object net.webclient).DownloadFile('http://www.nltk.org/nltk_data/packages/corpora/dependency_treebank.zip', 'c:\dependency_treebank.zip')
  - ps: mkdir c:\dependency_treebank
  - ps: unzip c:\dependency_treebank.zip -d c:\
  - ps: cd c:\
  - c:\msys64\usr\bin\cat /c/dependency_treebank/wsj_*.dp | c:\msys64\usr\bin\grep -v "^$" > c:\dependency_treebank\nltk-ptb.dp

build_script:
  - mkdir c:\b
  - cd c:\b
  - echo %BOOST_ROOT%
  - echo %BOOST_LIBRARYDIR%
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - cmake -G "Ninja" "-DCMAKE_PREFIX_PATH=%QTDIR%;%BOOST_ROOT%" "-DLIMA_RESOURCES=build" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=c:\d" "-DBOOST_ROOT:STRING=%BOOST_ROOT%" "-DBOOST_LIBRARYDIR:STRING=%BOOST_LIBRARYDIR%" -DCMAKE_IGNORE_PATH="C:/msys64/usr/bin" c:/projects/lima
  - cmake --build . --config Release

after_build:
  - ps: ls c:/d/share/apps/lima/tests
  - ps: pushd c:/d/share/apps/lima/tests
  - ps: ( tva --language=eng test-eng.tokenizer.xml test-eng.simpleword.xml test-eng.idiom.xml test-eng.abbrev.xml test-eng.hyphen.xml test-eng.default.xml test-eng.se-PERSON.xml test-eng.se-DATE.xml test-eng.se-EMBEDED.xml test-eng.se-ORGANISATION.xml test-eng.se.xml test-eng.se-LOCATION.xml test-eng.disambiguated.xml test-eng.sa.xml 2>&1 | tee tva-eng.log ) -or $true
  - ps: ( tva --language=fre test-fre.tokenizer.xml test-fre.simpleword.xml test-fre.hyphen.xml test-fre.idiom.xml test-fre.default.xml test-fre.se.xml test-fre.disambiguated.xml test-fre.sa.xml 2>&1 | tee tva-fre.log ) -or $true
  - ps: popd
  - ps: pushd C:\b\lima_common\src\lima_common-build
  - copy lima*-*.exe %APPVEYOR_BUILD_FOLDER%
  - ps: popd
  - ps: pushd C:\b\lima_linguisticprocessing\src\lima_linguisticprocessing-build
  - copy lima*-*.exe %APPVEYOR_BUILD_FOLDER%
  - ps: popd
  - ps: pushd C:\b\lima_linguisticdata\src\lima_linguisticdata-build
  - copy lima*-*.exe %APPVEYOR_BUILD_FOLDER%
  - ps: popd
  - ps: pushd C:\b\lima_gui\src\lima_gui-build
  - copy lima*-*.exe %APPVEYOR_BUILD_FOLDER%
  - ps: popd

before_deploy:
  - ps: pushd c:/projects/lima
  - ps: $env:DEPLOY_TAG="$(git log --date=iso  -1 | grep Date | sed -e 's/Date:\ *//' -e 's/\+.*//' -e 's/[- :]//g')-$(git log --format=%h -1)"
  - echo %DEPLOY_TAG%

artifacts: 
  - path: lima*.exe
    name: packages

deploy:
  description: '$(DEPLOY_TAG)'
  provider: GitHub
  tag: $(DEPLOY_TAG)
  auth_token:
    secure: 01sh5OxKgkUJbTt/ldX/duLQk6iP28Iwet3reW8FK8f7Z3xiM2RLHQUwOzZye4qs
  artifact: packages
  force_update: true


#on_failure:
         #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
